---
- name: Make gitlab runner
  hosts: runner
  tasks:
    - name: Install curl
      become: true
      apt:
        name: curl
        state: present
    - name: Check curl
      become: true
      shell: whereis curl
    - name: Get runner repo
      become_user: ditry
      shell: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
#    - name: Install runner repo
#      become: true
#      become_user: root
#      shell: bash /tmp/gitlab-runner-script.sh
    - name: Add the pinning configuration file
      become: true
      become_user: ditry
      shell: |
        cat <<EOF | sudo tee /etc/apt/preferences.d/pin-gitlab-runner.pref
        Explanation: Prefer GitLab provided packages over the Debian native ones
        Package: gitlab-runner
        Pin: origin packages.gitlab.com
        Pin-Priority: 1001
        EOF
    - name: Install docker requirememnts
      become: true
      apt:
        name:
          - ca-certificates
          - gnupg
        update_cache: true
        state: present
    # - name: Install docker repo
    #   become: true
    #   shell: |
    #     install -m 0755 -d /etc/apt/keyrings
    #     curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    #     chmod a+r /etc/apt/keyrings/docker.gpg
    #     echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Install docker
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
        state: present
    - name: Install runner
      become: true
      apt: 
        name: gitlab-runner
        state: present

- name: Gitlab server
  hosts: server
  tasks:
    - name: Print root password
      become: true
      shell: cat /etc/gitlab/initial_root_password
      register: out_pass.stdout_lines
    - debug: 
        var: out_pass