---
- name: Make gitlab runner
  hosts: runner
  tasks:
    - name: Install curl
      become: true
      apt:
        name: curl
        state: present
    - name: Check curl
      become: true
      shell: whereis curl
    - name: Get runner repo
      become_user: ditry
      shell: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
#    - name: Install runner repo
#      become: true
#      become_user: root
#      shell: bash /tmp/gitlab-runner-script.sh
    - name: Add the pinning configuration file
      become: true
      become_user: ditry
      shell: |
        cat <<EOF | sudo tee /etc/apt/preferences.d/pin-gitlab-runner.pref
        Explanation: Prefer GitLab provided packages over the Debian native ones
        Package: gitlab-runner
        Pin: origin packages.gitlab.com
        Pin-Priority: 1001
        EOF
    - name: Install runner
      become: true
      apt: 
        name: gitlab-runner
        update_cache: true
        state: present