---
runner:
  hosts:
    gitlab_runner:
      ansible_host: "{{ lookup('env','RUNNER') | ansible.utils.ipv4 }}"
  vars:
    ansible_connection_type: paramiko
    ansible_user: ditry
server:
  hosts:
    gitlab_server:
      ansible_host: "{{ lookup('env','SERVER') | ansible.utils.ipv4 }}"
  vars:
    ansible_connection_type: paramiko
    ansible_user: ditry